Repository spice-herald/QETpy, pull requests merged in 2018-12, with the labels that each got.

#13 remove calculation of timelen from optimum filters
  qetpy/core/_fitting.py
Labels: smallfix

#18 Add a class for efficient OF computation
  qetpy/core/_fitting.py
Labels: enhancement, refactor

#19 add more fall time options to fit_falltimes
  qetpy/core/_fitting.py
  qetpy/plotting/_plotting.py
  test/test_fitting.py
Labels: enhancement
