Repository spice-herald/QETpy, pull requests merged in 2019-02, with the labels that each got.

#32 Updated Fitting Demo
  .gitignore
  demos/fitting/fitting_demo.ipynb
  demos/fitting/psd.npy
  demos/fitting/pulse_fitting_example.ipynb
  demos/fitting/template.npy
  demos/fitting/trace.npy
  docs/example_demos/fitting_demo.rst
  docs/example_demos/fitting_demo_files/fitting_demo_16_0.png
  docs/example_demos/fitting_demo_files/fitting_demo_21_0.png
  docs/example_demos/fitting_demo_files/fitting_demo_30_0.png
  docs/example_demos/fitting_demo_files/fitting_demo_5_0.png
  docs/example_demos/pulse_fitting_example.rst
  docs/example_demos/pulse_fitting_example_files/pulse_fitting_example_11_0.png
  docs/example_demos/pulse_fitting_example_files/pulse_fitting_example_14_0.png
  docs/example_demos/pulse_fitting_example_files/pulse_fitting_example_19_0.png
  docs/example_demos/pulse_fitting_example_files/pulse_fitting_example_6_0.png
  docs/example_demos/pulse_fitting_example_files/pulse_fitting_example_6_1.png
  docs/examples.rst
Labels: documentation, maintenance

#36 Improved 3,4 pole functions in ofnonlin
  qetpy/core/_fitting.py
  test/test_fitting.py
Labels: improvement

#37 Feature/ofnsmb
  qetpy/core/_fitting.py
  qetpy/plotting/_plotting.py
Labels: feature

#39 Add default pre-commit hooks for linting and styling
  .pre-commit-config.yaml
  requirements.txt
Labels: maintenance

#41 add view code option, update version number
  docs/conf.py
Labels: documentation

#44 Split test_energy_absorbed into multiple tests
  test/test_utils.py
Labels: refactor

#43 Calculate mean once when calling slope function
  qetpy/utils/_utils.py
Labels: refactor

#42 add flexibility to window in ofamp_withdelay, add unit test
  qetpy/core/_fitting.py
  test/test_fitting.py
Labels: feature

#46 Evaluating mask using product of amp and pulse_direction_constraint
  qetpy/core/_fitting.py
Labels: refactor
