Repository spice-herald/QETpy, pull requests merged in 2019-06, with the labels that each got.

#67 Small bug fixing for get_muon_offset function
  qetpy/utils/_utils.py
Labels: bug, smallfix

#66 Add itercov function
  qetpy/cut/_cut.py
  test/test_cut.py
  test/test_utils.py
Labels: feature

#69 Add the optional calculation of the unbiased mean and standard deviation in iterstat
  qetpy/cut/_cut.py
  test/test_cut.py
  test/test_utils.py
Labels: feature, maintenance
