Repository spice-herald/QETpy, pull requests merged in 2019-03, with the labels that each got.

#48 Added bounds input option and fit success output to fit_falltimes
  demos/fitting/fitting_demo.ipynb
  qetpy/core/_fitting.py
Labels: feature, improvement

#52 Add make_template and shift functions to utils
  qetpy/utils/_utils.py
  test/test_utils.py
Labels: improvement

#56 fixed small bugs in noise class
  demos/noise/noise_example.ipynb
  qetpy/core/_noise.py
Labels: bug, smallfix

#57 Feature/ofnsmb
  demos/fitting/files/gradientproblem.png
  demos/fitting/files/timedomainproblem.png
  demos/fitting/of_nsmb_demo.ipynb
  qetpy/core/__init__.py
  qetpy/core/_fitting.py
  qetpy/core/_of_nsmb.py
  qetpy/plotting/_plotting.py
  qetpy/sim/__init__.py
  qetpy/sim/_sim_nsmb.py
  test/test_ofnsmb.py
Labels: feature

#58 Fix whitespace and move commonly used variables to module scope
  qetpy/sim/_sim_nsmb.py
Labels: refactor

#60 Moved test functions/sim OF nSmB functions to a new file
  demos/fitting/helpers.py
  demos/fitting/of_nsmb_demo.ipynb
  qetpy/sim/__init__.py
  test/helpers.py
  test/test_fitting.py
  test/test_ofnsmb.py
  test/test_utils.py
Labels: refactor

#61 Improvement/sim plotting
  demos/noise/noise_example.ipynb
  qetpy/plotting/_plotting.py
  setup.py
  test/test_detcal.py
Labels: improvement, refactor
