Repository spice-herald/QETpy, pull requests merged in 2019-01, with the labels that each got.

#24 Improved the tests for _fitting.py, added _argmin_chi2
  .gitignore
  qetpy/core/_fitting.py
  test/test_fitting.py
Labels: maintenance, refactor

#25 Add pulse direction constraint
  qetpy/core/_fitting.py
  test/test_fitting.py
Labels: bug, enhancement, maintenance

#28 Fix the pulse constraint bug when the constraint gives an empty array
  qetpy/core/_fitting.py
  test/test_fitting.py
Labels: bug

#26 Maintenance/array energy calc
  qetpy/utils/_utils.py
  test/test_utils.py
Labels: enhancement, maintenance, smallfix

#30 Refactor/energy absorbed
  qetpy/utils/_utils.py
  test/test_utils.py
Labels: refactor
